name = "BTA! packwiz example modpack"
author = "camoweed"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9476fba338c35248d9dcfa841abfcf3cd39e5c2e4524de8e0c47fff1fab4ade"

[versions]
bta = "8.0"
fabric = "0.18.4-bta.11"
minecraft = "b1.7.3"
unsup = "1.2.7"

[options]
acceptable-game-versions = ["b1.7.3"]
