name = "BTA! packwiz example modpack"
author = "camoweed"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a32efc303b90491cd129c0eae5c56c8e097b93eb64c06437a93bd4dd0a75dbe2"

[versions]
bta = "8.0"
fabric = "0.18.4-bta.11"
minecraft = "b1.7.3"
unsup = "1.2.7"

[options]
acceptable-game-versions = ["b1.7.3"]
