name = "BTA! packwiz example modpack"
author = "camoweed"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b17d9a0d7e04833b48f93cba0b8a35d3802e4a8515b57f5b8410193a8bec0d8"

[versions]
bta = "8.0"
fabric = "0.18.4-bta.11"
minecraft = "b1.7.3"
unsup = "1.2.7"

[options]
acceptable-game-versions = ["b1.7.3"]
